/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  leandroall
 * Created: 01/11/2017
 */

CREATE TABLE ADMINISTRADOR(
id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
nome VARCHAR(100) NOT NULL,
loggin VARCHAR(1024) NOT NULL,
senha VARCHAR(1024) NOT NULL,
CONSTRAINT adm_primary_key PRIMARY KEY (id)
) ;

CREATE TABLE CATEGORIA(
id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
descricao VARCHAR(8000) NOT NULL,
CONSTRAINT cat_primary_key PRIMARY KEY (id)
) ;


CREATE TABLE CLIENTE(
id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
nome VARCHAR(100) NOT NULL,
idade INTEGER NOT NULL,
endereco VARCHAR(1024) NOT NULL,
bairro VARCHAR(1024) NOT NULL,
cidade VARCHAR(1024)NOT NULL,
estado VARCHAR(1024) NOT NULL,
cpf VARCHAR(50) NOT NULL,
rg VARCHAR(50) NOT NULL,
sexo VARCHAR(1) NOT NULL,
estado_civil VARCHAR(1) NOT NULL,
email VARCHAR(100) NOT NULL,
telefone VARCHAR(20) NOT NULL,
numero_cartao VARCHAR(50) NOT NULL,
bandeira_cartao VARCHAR(1)NOT NULL,
loggin VARCHAR(1024) NOT NULL,
senha VARCHAR(1024) NOT NULL,
CONSTRAINT cli_primary_key PRIMARY KEY (id)
) ;


CREATE TABLE PRODUTO(
id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
nome VARCHAR(100) NOT NULL,
descricao VARCHAR(8000)NOT NULL,
valor DOUBLE NOT NULL,
id_categoria INTEGER NOT NULL,
CONSTRAINT prod_primary_key PRIMARY KEY (id),
CONSTRAINT fk_id_categoria FOREIGN KEY  (id_categoria) REFERENCES CATEGORIA(id)
) ;

CREATE TABLE COMPRAS(
id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
id_cliente INTEGER NOT NULL,
id_produto INTEGER NOT NULL,
CONSTRAINT comp_primary_key PRIMARY KEY (id),
CONSTRAINT fk2_id_cliente FOREIGN KEY  (id_cliente) REFERENCES CLIENTE(id),
CONSTRAINT fk_id_produto FOREIGN KEY (id_produto) REFERENCES PRODUTO(id)
) ;